# Generated by Django 5.1.7 on 2025-03-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_grievancelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grievance', 'verbose_name_plural': 'Grievances'},
        ),
    ]
