# Generated by Django 5.0.2 on 2025-04-12 10:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0004_alter_grievance_options'),
        ('users', '0005_update_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='issue_type',
            field=models.CharField(choices=[('TECHNICAL', 'Technical Issues'), ('CUSTOMER_SERVICE', 'Customer Service Issues'), ('SOFTWARE_BUG', 'Software/Application Bugs'), ('PRODUCT', 'Product/Feature Issues'), ('QUALITY', 'Quality Assurance Failures')], max_length=50),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating must be between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='grievances.grievance')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
