# Generated by Django 5.1.7 on 2025-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0006_alter_grievance_status_alter_grievanceupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='escalation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
